summary(week2.dataset)
var(week2.dataset) 
sqrt(var(week2.dataset))
sd(week2.dataset)
IQR(week2.dataset)
(sum(week2.dataset))/(length(week2.dataset))
length(week2.dataset)
(sum(sort(week2.dataset)[50:51]))/2
mode(week2.dataset)
boxplot(week2.dataset)
hist(week2.dataset)
density(week2.dataset)
week2.dataset<0
week2.dataset[week2.dataset<0]
tmp.week2data[tmp.week2data<0]
tmp.week2data[tmp.week2data<0]<-NA
sd(sort(tmp.week2data))
mean(sort(tmp.week2data))
log(week2.dataset)
hist(log10(sort(tmp.week2data)))
boxplot(log10(sort(tmp.week2data)))
mean(log10(sort(tmp.week2data)))
sd(log10(sort(tmp.week2data)))
